### ISSUE TITLE
Exception in documents "empty" page

### ISSUE THREAD

**Issue by pavel-mironchik** [akaunting/akaunting#1752]
### Steps to reproduce the issue
1. Install Credit/Debit Notes module or delete all debit notes if it is already installed.
2. Open `credit-debit-notes/debit-notes` route.

### Expected result
The "empty" page is shown.

### Actual result
Exception is thrown.

### System information (Akaunting, PHP versions)
Akaunting 2.1
PHP 7.4

### Additional comments
![2021-01-13 16-08-57 Ubuntu Mate 19 10 (Снимок 203)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104438582-5a2b5780-55ba-11eb-8ae7-1e92b00dd5f4.png)

This view doesn't take into account the module's alias: https://github.com/akaunting/akaunting/blob/master/resources/views/partials/admin/empty_page.blade.php

**Comment by cuneytsenturk** [comment]
Hi @pavel-mironchik I've fixed it, Please check it.

**Comment by pavel-mironchik** [comment]
A few glitches persist. I guess this requires changes in the blade file I've mentioned above.

![2021-01-13 17-07-13 Ubuntu Mate 19 10 (Снимок 203)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104444446-015fbd00-55c2-11eb-8a24-4fd641958693.png)

**Comment by pavel-mironchik** [comment]
> A few glitches persist. I guess this requires changes in the blade file I've mentioned above.

@cuneytsenturk this is just a friendly reminder in case you missed my previous message
