### ISSUE TITLE
Ability to add items to Invoices/Bills on mobile/iPhone doesn't work

### ISSUE THREAD

**Issue by rkemper** [akaunting/akaunting#1861]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

On an iPhone using Safari

1. Go to Sales -> Invoices
2. Click "Add New"
3. Select a Customer
4. Scroll down to Items section, click "Add an Item"
5. Click on an item, or search for a specific item and select it

Same steps, but when creating a Bill

### Expected result

Item is added to Invoice

Item is added to Bill

### Actual result

Selection List disappears, but item is not added to invoice.

Same result when attempting to add items to a bill.

### System information (Akaunting, PHP versions)

- iPhone XR (Also tested with same result on iPhone XS)
- iOS 14.4 (On both phones)
- Akaunting 2.1.2
- PHP 7.4

### Additional comments

- Not sure if this is a responsive issue, or browser issue.  I also tested using Firefox 85.0 on Ubuntu 18.04 using the Inspect Element Responsive Design mode emulating iPhone X/XS and the functionality works as expected.
- User owns/operates a cleaning business, and would like to be able to manage invoices for clients while they are at the client's location, so being able to do this from mobile is crucial to their business operations.

**Comment by onyet** [comment]
Same here. 
I hope this feedback is given action soon.
Thanks to the Akaunting team. because the application made is very helpful in our accounting process.

**Comment by cuneytsenturk** [comment]
I've fixed styling, and test it every thing works. I'll release new version, please test it.

**Comment by rkemper** [comment]
Still doesn't seem to be working on iPhone after updating?  In portrait mode, it doesn't show any results after searching for an item.  In landscape mode, it shows the results, but after selecting an item, it doesn't get added to the invoice.

**Comment by usvi4me** [comment]
This challenge still exists on the iPhone 12 Max running iOS 14.4.1.
In portrait mode no items are listed when clicking the + button. In landscape mode the items are listed but when selected the item does not appear on the invoice.
