### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by Davebrichi** [akaunting/akaunting#394]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I added a new user as manager

### Expected result
I should be redirected to the home page after entering my login details

### Actual result
The page remains static, it doesn't redirect me to the home page. I  have tried to reset password and entered the new password but the page still isn't redirecting.
I have cleared my cache, deleted the new user from the database, deleted images from the back end yet the issue remains. 
Got had a similar issue after uploading pictures for new items so i deleted and reinstalled Akaunting. Now after installation, i tried to add new user image and then logged out and tried to login but the page didn't redirect using any of the user details.

I have tried login on mozila and internet explorer but the problem persists. Please help

### System information (Akaunting, PHP versions)
Akaunting, PHP version 1.2.7

**Comment by Davebrichi** [comment]
I have deleted and re-installed Akaunting without changing images anywhere on the software. 
This time i only installed the software, changed currency, updated user details without changing images.  yet the issue persists. What am i doing wrong?.

On my first installation, i accepted an option to remember password; could this be the problem?
Please help!

**Comment by denisdulici** [comment]
This has been fixed here https://github.com/akaunting/akaunting/issues/386

**Comment by Davebrichi** [comment]
Thanks @denisdulici for your help but the issue persists. The issue is such that once i log out of the homepage, i cannot login. The page remains static; even after resetting the password.

I don't have a problem with adding new users but i can't log into the software after logging out; nothing happens after entering my login details.

**Comment by Davebrichi** [comment]
I deleted and re-installed Akaunting and the issue remained so i contacted my hosting company, they said they had resolved the issue. I have tried severally and this time i get error message: "Whoops, looks like something went wrong."

So i opened the error-log and found this line of code:

'Illuminate\View\Concerns\ManagesLayouts' not found in /home/rocsolac/public_html/vendor/laravel/framework/src/Illuminate/View/Factory.php on line 18

I have sent my hosting company series of mails but i'm just unhappy with the progress of events.
Please how do i resolve this issue?

**Comment by Davebrichi** [comment]
The issue has been resolved. The issue was with my host service provider. They fiddled with the files whilst activating mysql extension at installation.
