### ISSUE TITLE
Tax rates should not be rounded

### ISSUE THREAD

**Issue by MagicFab** [akaunting/akaunting#442]
When specifying a non-integer tax rate in Settings > Tax Rates, the value is rounded. It should not be rounded.

In Quebec, Canada, the provincial tax is 9.975%. When saving, this results in a tax rate of 10%.

I am using Akaunting online (app.akauting.com).

**Comment by batuhawk** [comment]
Hi Fabian,
This problem is solved with last version in github. I tested, please check again.

**Comment by MagicFab** [comment]
Thanks for the follow-up. Has this been deployed to https://app.akaunting.com/ ? The problem remains. I made a screencast (see attached).

[Screencast_2018-09-05_09:58:39.zip](https://github.com/akaunting/akaunting/files/2353045/Screencast_2018-09-05_09.58.39.zip)

**Comment by sirmyron** [comment]
I think this needs to be reopened... it's still an issue in version 1.3.10 or at least on the cloud version.
